print("A Day in NYC: A Mad Lib.")
print("We're gonna play a little game if you're up for it! I'm going to ask you for nouns, verbs, adjectives, proper nouns and adverbs. This will create a fun story using your words!")
proper_noun = input("Enter a proper noun: ")
place = input("Enter a place: " )
Another_place = input("Enter another place: ")
adverb = input("Enter an adverb: ")
noun = input("Enter a noun: ")
Adjective = input("Enter an adjective: ")
adverb2 = input("Enter an adverb: ")
verb = input("Enter a verb: ")
place_3 = input("Enter a third place: ")
Adjective2 = input("Enter another adjective: ")
print(f"Our famous Bikini Bottom hero, {proper_noun} is a {Adjective2} {noun} was {adverb} {adverb2} {verb} down the street this morning, on her way to the {Another_place} until she saw the great {place}. It was so {Adjective}, it looks just like the {place_3}. She was gawking at it until it came down and landed on our hero...The End!  ")